### ISSUE TITLE
Update connectors eureka-client library

### ISSUE THREAD

**Issue by dyroberts** [pivotal-cf/spring-cloud-services-starters#104]
To Spring Cloud Greenwich.SR3

**Comment by csterwa** [comment]
@dyroberts I believe with the release of Spring Cloud Greenwich.SR3 this is no longer blocked. I have moved it to high priority.

**Comment by spikymonkey** [comment]
Since Raul is no longer with us I'll move this back to the backlog

**Comment by csterwa** [comment]
@dyroberts is this in progress?

**Comment by csterwa** [comment]
@dyroberts SR4 just came out. Do we need another upgrade story for that?

**Comment by dyroberts** [comment]
@csterwa Yes, let's do that. I think this present release needs to get out the door, unless the SR4 upgrade is urgent?

**Comment by csterwa** [comment]
I'm not sure it is urgent but it might be a good idea to review the issues resolved list after your release to see if we need to do a quick patch release on 3.0.0.
