### ISSUE TITLE
Possibility of scoping BootStrapConfiguration when CloudFoundry is the cloud provider

### ISSUE THREAD

**Issue by xyloman** [pivotal-cf/spring-cloud-services-starters#121]
When teams deployed the same artifact in a variety of venues (e.g. CF or k8s or VMS or running locally) It appears but I could be misunderstanding this that the BootStrapConfiguration class is loaded regardless if CloudProvider is equal to cloud foundry environment.  Therefore, this leads to the properties file "classpath:/io/pivotal/spring/cloud/config/client/app-name.properties" to be loaded as a property source.  This in turn results in a property placeholder evaluation:

```
spring.application.name=${vcap.application.name:}
```

This evaluation results in spring.application.name to be set to '' in some use cases. 

https://github.com/pivotal-cf/spring-cloud-services-starters/blob/master/spring-cloud-services-config-client-autoconfigure/src/main/java/io/pivotal/spring/cloud/config/client/BootStrapConfiguration.java

**Comment by dyroberts** [comment]
spring-cloud-services is only available on pcf. That said, I believe setting the spring.application.name property anywhere else will override this property. @xyloman, are you running into a situation where that's not the case?

**Comment by xyloman** [comment]
I had a team member that had to deploy the same artifact on K8s as well as cf and saw an issue where this would create issues out side of cf

**Comment by dyroberts** [comment]
Since we've dropped spring-cloud-connectors in favour of java-cfenv, there is no longer the concept of CloudProvider. I think a work-around for this specific issue would be to set the `spring.application.name` property in your own application properties. This should override the bootstrap config. Please let us know here if you have problems with this approach.

**Comment by maximusfloydus** [comment]
With `spring-cloud-services-starters` 3.1.0.RELEASE` and `java-cfenv` 2.1.0.RELEASE I had to manually set both of these in the application.yml file to make the same SpringBoot jar to work in PCF and k8s.  FYI: We are transitioning to PCF deployments, but must have the same packages work in k8s for the long transition time.

```
vcap.application.name: 'MyContainer'

spring:
  application:
    name: 'MyContainer'
```

Is there another work around to force it to use java-cfenv vs spring-cloud-connectors?

**Comment by dyroberts** [comment]
spring-cloud-connectors are no longer included in the scs starters. So you shouldn't have to worry about that. Also, scs starters brings the java-cfenv dependency; so you shouldn't need to add that dependency explicitly.

**Comment by dyroberts** [comment]
@maximusfloydus I've just tested it with a sample app. You should just need to set the `spring.application.name` property and not the `vcap.application.name`.

**Comment by maximusfloydus** [comment]
You can close this for now.  I haven't had a chance to recreate the issue since I first experienced it.
