### ISSUE TITLE
VaultPropertyMaskingContextInitializer prevents configuration of "keys-to-sanitize"

### ISSUE THREAD

**Issue by datagitlies** [pivotal-cf/spring-cloud-services-starters#122]
### This is an issue for:
`io.pivotal.spring.cloud : spring-cloud-services-config-client-autoconfigure : 3.1.0.RELEASE` 

### Scenario
Let's say I have a secret stored in Vault called `my.important.api-key` which I do not want displayed in plan text on any of the [Spring Boot Actuator Endpoints](https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html#production-ready-endpoints). In order to prevent the plain text value from appearing on the `env` endpoint I could add the below [property](https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#actuator-properties) inside the `application.properties` file:

<pre>management.endpoint.env.keys-to-sanitize=<b>api-key</b>,password,secret,key,token,.*credentials.*,vcap_services</pre>

### Problem
The above property is overridden by the [`VaultPropertyMaskingContextInitializer`](https://github.com/pivotal-cf/spring-cloud-services-starters/blob/master/spring-cloud-services-config-client-autoconfigure/src/main/java/io/pivotal/spring/cloud/config/client/VaultPropertyMaskingContextInitializer.java#L96) which is adding a `PropertySource` with the name "management.endpoint.env.keys-to-sanitize" of type `PropertiesPropertySource` **at the  highest precedence.**

<pre>environment.getPropertySources().<b>addFirst</b>(envKeysToSanitize);</pre>

The end result is that the `env` actuator endpoint will display `my.important.api-key` in plain text and I'm stuck because I am unable to provide the `management.endpoint.env.keys-to-sanitize` property in `application.properties` or by any other means because it will always be at a lower precedence than what the [`VaultPropertyMaskingContextInitializer`](https://github.com/pivotal-cf/spring-cloud-services-starters/blob/master/spring-cloud-services-config-client-autoconfigure/src/main/java/io/pivotal/spring/cloud/config/client/VaultPropertyMaskingContextInitializer.java#L96) provides.

### Potential Solution
Change the [`VaultPropertyMaskingContextInitializer`](https://github.com/pivotal-cf/spring-cloud-services-starters/blob/master/spring-cloud-services-config-client-autoconfigure/src/main/java/io/pivotal/spring/cloud/config/client/VaultPropertyMaskingContextInitializer.java#L96) so it uses the lowest precedence:

<pre>environment.getPropertySources().<b>addLast</b>(envKeysToSanitize);</pre>

**Comment by dyroberts** [comment]
@datagitlies Nice catch. Thanks for the contribution.

**Comment by dyroberts** [comment]
@datagitlies we've released v3.1.1.RELEASE that includes this change. ;)

**Comment by datagitlies** [comment]
@dyroberts I pulled it into my project yesterday :)  Thanks for the quick turnaround on a new release!
