### ISSUE TITLE
Upgrade 2.x to boot 2.2.x

### ISSUE THREAD

**Issue by dyroberts** [pivotal-cf/spring-cloud-services-starters#127]
Due to potential incompatibilities with the java-buildpack, we need to keep the 2.x line alive for a while.

**Comment by csterwa** [comment]
@dyroberts is there a PR attached to this? Also, Is the Boot 2.2.x upgrade only for SCS Starters 2.2.x?

**Comment by dyroberts** [comment]
@csterwa Yes, starters 2.2 = boot 2.2, starters 2.1 = boot 2.1.

**Comment by dyroberts** [comment]
@csterwa PR, no.

**Comment by dyroberts** [comment]
I was just bumping dependency versions and running ATs; so I didn't see the need for a PR.
