### ISSUE TITLE
Upgrade gradle maven-plugin for connectors

### ISSUE THREAD

**Issue by dyroberts** [pivotal-cf/spring-cloud-services-starters#129]
We need to publish a pom with resolved dependency versions and no boms/dependencyManagement.

**Comment by csterwa** [comment]
@dyroberts is there a PR attached to this?

**Comment by dyroberts** [comment]
@csterwa No PR. I pushed the changes and diffed the poms that were deployed to artifactory with versions from previous successful builds.
