### ISSUE TITLE
Discovery-first approach for Config server failing with Http error 401

### ISSUE THREAD

**Issue by hiren-intellectdesign** [pivotal-cf/spring-cloud-services-starters#13]
There are couple of Spring Cloud services available in Pivotal Cloud Foundry (CF):

1. `p-service-registry` (Spring Cloud Eureka)
2. `p-config-server` (Spring Cloud Config Server)

Here, we are aiming to build discovery-first approach for our Springboot client applications.

What we have done so far in CF is:

a. Bring up Eureka CF service (**works OK**)

- Using CF Service `p-service-registry`
- This by default, requires OAuth2 authentication by client application

b. Bring up Config Server (**works OK**)

- This is our own Springboot annotated application (using `@EnableConfigServer`), which connects to our own Git repository to serve the configuration
- It registers itself with Eureka during startup
	- uses `spring-cloud-services-starter-service-registry`
	- uses `@EnableDiscoveryClient`
	- flag `eureka.client.enabled` = true
- registers with Eureka with name as "sb-config-server"
- Config Server requires Http Basic Authentication by Client application wanting to fetch the configuration

c. Bring up Client application (**Fails with Error 401**)

- This is our own Springboot annotated client application
- It registers itself with Eureka during startup
	- uses spring-cloud-services-starter-service-registry
	- uses @EnableDiscoveryClient
	- flag eureka.client.enabled = true
- what we additionally require is, Config Server should also be discovered during Eureka registration process [**This is where the problem is**]
	- we added dependency on `spring-cloud-services-starter-service-registry`
	- we have set `spring.cloud.config.discovery.enabled` to true
	- we have set `spring.cloud.config.discovery.serviceId` correctly to "sb-config-server"
	- for Config Server, we have set Http Basic Authentication parameters - `eureka.instance.metadataMap.username` to "user" and `eureka.instance.metadataMap.password` to <<appropriate-password>>
- Problem is we are getting Http Error code 401 during Config Server discovery process (as a result, Eureka registration fails)

	
**Error 401:**

```text
:
2017-10-18T10:33:25.97+0530 [APP/PROC/WEB/0]OUT 2017-10-18 05:03:25,971 DEBUG [main] com.netflix.discovery.shared.transport.jersey.AbstractJerseyEurekaHttpClient (<init>:42) - Created client for url: https://eureka-4ad7d239-9023-4a8c-a11f-18ad4afd4d02.cfapps.io/eureka/
2017-10-18T10:33:26.29+0530 [APP/PROC/WEB/0]ERR 	at com.netflix.discovery.DiscoveryClient.<init>(DiscoveryClient.java:444) [eureka-client-1.4.12.jar!/:1.4.12]
2017-10-18T10:33:26.28+0530 [APP/PROC/WEB/0]OUT 2017-10-18 05:03:26,289 DEBUG [main] com.netflix.discovery.shared.transport.decorator.RedirectingEurekaHttpClient (executeOnNewServer:121) - Pinning to endpoint null
2017-10-18T10:33:26.29+0530 [APP/PROC/WEB/0]OUT 2017-10-18 05:03:26,289 WARN  [main] com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient (execute:127) - Request execution failure with status code 401; retrying on another server if available
2017-10-18T10:33:26.29+0530 [APP/PROC/WEB/0]ERR 2017-10-18 05:03:26,289 WARN  [main] com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient (execute:127) - Request execution failure with status code 401; retrying on another server if available
2017-10-18T10:33:26.29+0530 [APP/PROC/WEB/0]OUT 2017-10-18 05:03:26,290 ERROR [main] com.netflix.discovery.DiscoveryClient (fetchRegistry:951) - DiscoveryClient_SB-CLIENT/94ba527c-51b6-4050-46d8-bf4e - was unable to refresh its cache! status = Cannot execute request on any known server
2017-10-18T10:33:26.29+0530 [APP/PROC/WEB/0]OUT com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
2017-10-18T10:33:26.29+0530 [APP/PROC/WEB/0]OUT 	at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:111) ~[eureka-client-1.4.12.jar!/:1.4.12]
:
```
---

**Other observation** is, if we **disable** Config Server discovery (i.e. if we comment flag `spring.cloud.config.discovery.enabled`) , then error 401 goes away. Client application registers successfully with Eureka (but without Config Server discovery).

```text
:
2017-10-18T10:38:51.73+0530 [APP/PROC/WEB/0]OUT 2017-10-18 05:08:51,739 DEBUG [main] com.netflix.discovery.shared.transport.jersey.AbstractJerseyEurekaHttpClient (<init>:42) - Created client for url: https://eureka-4ad7d239-9023-4a8c-a11f-18ad4afd4d02.cfapps.io/eureka/
2017-10-18T10:38:52.21+0530 [APP/PROC/WEB/0]OUT 2017-10-18 05:08:52,215 DEBUG [main] com.netflix.discovery.shared.transport.jersey.AbstractJerseyEurekaHttpClient (getApplicationsInternal:206) - Jersey HTTP GET https://eureka-4ad7d239-9023-4a8c-a11f-18ad4afd4d02.cfapps.io/eureka//apps/?; statusCode=200
2017-10-18T10:38:52.21+0530 [APP/PROC/WEB/0]OUT 2017-10-18 05:08:52,216 DEBUG [main] com.netflix.discovery.shared.transport.decorator.RedirectingEurekaHttpClient (executeOnNewServer:121) - Pinning to endpoint null
2017-10-18T10:38:52.21+0530 [APP/PROC/WEB/0]OUT 2017-10-18 05:08:52,216 INFO  [main] com.netflix.discovery.DiscoveryClient (getAndStoreFullRegistry:1035) - The response status is 200
2017-10-18T10:38:52.21+0530 [APP/PROC/WEB/0]OUT 2017-10-18 05:08:52,216 DEBUG [main] com.netflix.discovery.DiscoveryClient (getAndStoreFullRegistry:1041) - Got full registry with apps hashcode UP_1_
:
```

![service-registry](https://user-images.githubusercontent.com/20412715/31711915-3fed7922-b417-11e7-875d-ac6e9950bfbb.png)

---

What could be the issue here?

Is there any limitation with "spring-cloud-services-starter-service-registry" that prevents us from discovering our own Config Server? (resulting in error 401)

Is there any working example of Discovery-first approach that works with Eureka and Custom Spring Config Server?

**Comment by daniellavoie** [comment]
Hi @hiren-intellectdesign 

The problem you are facing comes from the fact that the Service Registry (Eureka) is protected by OAuth2. OSS Spring Cloud Config Client offers no out of the box support for OAuth2. The basic credentials you have supplied in the Eureka client configuration won't work. On SCS Config Client, we don't support Discovery First as the client application binds itself to the Config Server through PCF `VCAP_SERVICES` env variables.

Do you have any specific reason to not use the SCS Config Server? As a PCF service, it could be bound to your app, preventing the need to use discovery first from the Config Client.

If for some reason, you still need a custom config server, you will have to manually configure your config server route for each application. Again, careful with security as the OSS config client does not support OAuth2.

**Comment by hiren-intellectdesign** [comment]
Hi, Thanks for reply.

> The problem you are facing comes from the fact that the Service Registry (Eureka) is protected by OAuth2. OSS Spring Cloud Config Client offers no out of the box support for OAuth2. The basic credentials you have supplied in the Eureka client configuration won't work. On SCS Config Client, we don't support Discovery First as the client application binds itself to the Config Server through PCF VCAP_SERVICES env variables.

As mentioned in my "Other Observation" section, Service Registry already **works for me** even in OAuth2 mode (if I disable `spring.cloud.config.discovery.enabled`). My client application is able to register with Eureka successfully, using "spring-cloud-services-starter-service-registry" and VCAP_SERVICES.

> Do you have any specific reason to not use the SCS Config Server? As a PCF service, it could be bound to your app, preventing the need to use discovery first from the Config Client.

Pls consider that Discovery-First is our requirement (changing this is rare possibility). We are following instruction [here](http://cloud.spring.io/spring-cloud-config/single/spring-cloud-config.html#discovery-first-bootstrap). For Config Server, we aren't using PCF service, as we don't know how to register "p-config-server" service with "p-service-registry" service. Couldn't find any option [here](https://docs.pivotal.io/spring-cloud-services/1-4/common/config-server/).


> If for some reason, you still need a custom config server, you will have to manually configure your config server route for each application. Again, careful with security as the OSS config client does not support OAuth2.

As mentioned (in original post), we already have custom Config Server, which is configured with Http Basic Authentication requirement (not OAuth2). And we are supplying credentials in client application using `eureka.instance.metadataMap.username` and `eureka.instance.metadataMap.password` parameters. And that's why unable to understand, why even after following correct instructions, we get error 401 only when we go for discovery-first approach (i.e. enabling `spring.cloud.config.discovery.enabled` flag in client application).

On more point to note is, this whole setup works perfectly fine on local machine, using the same parameters. It is only when we start using PCF instances and SCC Starters, client app fails with error 401.

Just to summarize (for better clarity):
Our own Config Server -> registering -> PCF Eureka (**works**)
Our own Client App -> registering -> PCF Eureka (also **works**)
But,
Client App -> registering -> PCF Eureka, to discover Config Server (fails with **401**)

I think, there is some silly point which is missed out here (don't believe it is a bug anywhere), but not able to pinpoint. Even logs (shared earlier) doesn't help much than just saying it got 401 error during registration process. :(

**Comment by daniellavoie** [comment]
I'll repeat, Spring Cloud Service does not support Discovery First for the Config Client.

The reason is that the config client starts up your Spring Boot Application with a Bootstrap Container. In that bootstrap container, auto-config instantiates a stand-alone eureka client that looks up Eureka for the config server. You are receiving a 401 from Eureka because your client tries Basic Auth rather than OAuth2. 

We provide support for service discovery only once the configuration has been loaded. We don't provide any OAuth2 credentials for the bootstrap eureka-client. Only for the one use by the main spring container.

**Comment by hiren-intellectdesign** [comment]
> I'll repeat, Spring Cloud Service does not support Discovery First for the Config Client.

Ok, Thanks for further clarification and more details.

But this contradicts what I read here - http://cloud.spring.io/spring-cloud-config/single/spring-cloud-config.html#discovery-first-bootstrap

Is what written here, not supported yet, you mean to say? Or I am misinterpreting?

> I still don't understand why registering a Config Server to Eureka is a requirement. Service binding with PCF suppress the need for service discovery for the config server.

The reason for discovery first approach, is that we expect config-server to switch at some point (and it may switch to Non-PCF one too). Nevertheless, that can't be the reason for above to not work.

**Comment by daniellavoie** [comment]
Spring Cloud Services aims to provide client integration to PCF Service Registry and PCF Config Server. For that echo-system, discovery first is irrelevant. 

Spring Cloud and Spring Cloud Services are two different projects. If you are not interested in PCF Config Server, I would recommend you to implement your own Eureka server that is not protected with OAauth2.

**Comment by hiren-intellectdesign** [comment]
@daniellavoie Ok. Noted.

@scottfrederick Thanks for nailing down on the problem.

> When you use `spring.cloud.config.discovery.enabled=true` in the client app, code in open-source Spring Cloud is attempting to access eureka, but that code doesn't know about OAuth2. That appears to be what's causing the 401. This is a gap between SCS and open-source that we haven't encountered before, and we don't have a way to address it at this time.

This explains it for me. Clearly, I was assuming that SCS adds on to what is already supported under open-source Spring Cloud. Except, in this case.

Thanks for clarifying. That helps us knowing our next step (which is custom Eureka server, without OAuth2 authentication - I believe, OAuth2 is not optional in PCF, right?).

The above gap, do you think, qualifies for a fix in near future? Or it is not intended/compliant for SCS world?
