### ISSUE TITLE
Vault token renewal RestTemplate is not properly qualified

### ISSUE THREAD

**Issue by Walliee** [pivotal-cf/spring-cloud-services-starters#134]
After upgrading to `spring-cloud-services-starter-config-client:3.1.1.RELEASE`, our application failed to startup with the following error:

```
The bean 'restTemplate', defined in class path resource [io/pivotal/spring/cloud/config/client/VaultTokenRenewalAutoConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [com/example/WebConfig.class] and overriding is disabled.
```

While I was able to get past it by qualifying my RestTemplate bean to a name other than "restTemplate", it seems like the intention in `VaultTokenRenewalAutoConfiguration` was to qualify the RestTemplate as `vaultTokenRenewal` but it's not working as using `@Qualifier` on an `@Bean` annotated method doesn't register the bean under the value of `@Qualifier` annotation.

https://github.com/pivotal-cf/spring-cloud-services-starters/blob/7a57be95869487b06fcd2477f8d31ea1962a01ed/spring-cloud-services-config-client-autoconfigure/src/main/java/io/pivotal/spring/cloud/config/client/VaultTokenRenewalAutoConfiguration.java#L86-L90

**Comment by dyroberts** [comment]
While the use of the `@Qualifier()` annotation was intentional here, I think you're right that the bean name is unnecessarily generic.
