### ISSUE TITLE
vault refresher could log too much in obscuredToken

### ISSUE THREAD

**Issue by nhomble** [pivotal-cf/spring-cloud-services-starters#135]
In [this config](https://github.com/pivotal-cf/spring-cloud-services-starters/blob/master/spring-cloud-services-config-client-autoconfigure/src/main/java/io/pivotal/spring/cloud/config/client/VaultTokenRenewalAutoConfiguration.java)
The refresher always logs an obscuredToken
```
		public void refreshVaultToken() {
			try {
				LOGGER.info("Renewing Vault token " + obscuredToken + " for " + renewTTL + " milliseconds.");
				restTemplate.postForObject(refreshUri, request, String.class);
			} catch (RestClientException e) {
				LOGGER.error("Unable to renew Vault token " + obscuredToken + ". Is the token invalid or expired?");
			}
		}
```
where the token is defined by
```
String obscuredToken = vaultToken.substring(0, 4) + "[*]" + vaultToken.substring(vaultToken.length() - 4);
```
vault token comes directly via the environment
```
@Value("${spring.cloud.config.token}") String vaultToken,
```

--
It's dangerous to hardcode 4 as the truncating factor since nothing is validating the length of the vault token. 
If we want to log this at info, we should respect the varying size of the string, or delegate this to debug which commonly has sensitive info.

To illustrate the point, 
```
String vaultToken = "123456789";
vaultToken.subString(0, 4) + "[*]" + vaultToken.subString(vaultToken.length() - 4)

"1234[*]6789"
```

**Comment by dyroberts** [comment]
Vault tokens are generated by vault itself. I believe the length will be at least 36 characters, up to 200+ characters. That said, moving to DEBUG log level seems reasonable.
