### ISSUE TITLE
BinaryResourceConfigClient missing in spring-cloud-services-starter-config-client:3.x.x

### ISSUE THREAD

**Issue by Walliee** [pivotal-cf/spring-cloud-services-starters#140]
As part of [spring-cloud-services-connector#120](https://github.com/pivotal-cf/spring-cloud-services-connector/issues/120), support for retrieving binary resources was added to [spring-cloud-services-spring-connector](https://github.com/pivotal-cf/spring-cloud-services-connector/tree/master/spring-cloud-services-spring-connector). 

It appears as part of the refactor to use `java-cfenv` in [spring-cloud-services-starter-config-client](https://github.com/pivotal-cf/spring-cloud-services-starters/tree/master/spring-cloud-services-starter-config-client), the dependency on `spring-cloud-services-spring-connector` was removed. 

Also, as part of the refactor, some files that were previously sourced from `spring-cloud-services-spring-connector` were moved to [spring-cloud-services-config-client-autoconfigure](https://github.com/pivotal-cf/spring-cloud-services-starters/tree/master/spring-cloud-services-config-client-autoconfigure/src/main/java/io/pivotal/spring/cloud/config/client).

However, looks like the files that were moved were not from what was latest on the master branch. As such, changes to support [spring-cloud-services-connector#120](https://github.com/pivotal-cf/spring-cloud-services-connector/issues/120) are missing in the latest version (3.x.x) of `spring-cloud-services-starter-config-client`.

**Comment by Walliee** [comment]
@dyroberts @habuma thoughts?

**Comment by Walliee** [comment]
@dyroberts @habuma Appreciate if you can help resolve this. We are unable to upgrade apps take use `BinaryResourceConfigClient` to 3.x.x.

**Comment by dyroberts** [comment]
@Walliee Sorry for the delay. We've got this in our backlog and should be able to get to it soon.

**Comment by Walliee** [comment]
No worries - Thanks for looking into this!

**Comment by dyroberts** [comment]
This is included in v3.1.3.RELEASE
