### ISSUE TITLE
Upgrade 3.x to spring-boot 2.4.1

### ISSUE THREAD

**Issue by dyroberts** [pivotal-cf/spring-cloud-services-starters#172]

**Comment by dyroberts** [comment]
This is done on master but not yet validated with an AT run on CI (or anywhere else).

**Comment by datagitlies** [comment]
@dyroberts is there a `SNAPSHOT` build of `spring-cloud-services-dependencies` or `spring-cloud-services-starter-config-client` with the spring-boot 2.4 changes in it?  I'd be willing to test this out in my project and report back.

**Comment by dyroberts** [comment]
@datagitlies Yes! v3.2.0.BUILD-SNAPSHOT

**Comment by datagitlies** [comment]
@dyroberts do you publish the `SNAPSHOT` builds anywhere?  I [don't see anything](https://mvnrepository.com/artifact/io.pivotal.spring.cloud/spring-cloud-services-dependencies) in [maven central](https://mvnrepository.com/artifact/io.pivotal.spring.cloud/spring-cloud-services-starter-config-client).

**Comment by dyroberts** [comment]
> @dyroberts do you publish the `SNAPSHOT` builds anywhere? I [don't see anything](https://mvnrepository.com/artifact/io.pivotal.spring.cloud/spring-cloud-services-dependencies) in [maven central](https://mvnrepository.com/artifact/io.pivotal.spring.cloud/spring-cloud-services-starter-config-client).

https://www.baeldung.com/spring-maven-repository

**Comment by nniesen** [comment]
What's the ETA on this? Looking for a ballpark; couple weeks or couple months. This is the final piece to upgrading ~100 microservices from 2.1 and would rather not have to stop at 2.3 if it's soon.

**Comment by dyroberts** [comment]
> Do you have an ETA on this? Looking for a ballpark; couple weeks or couple months. This is the final piece to upgrading ~100 microservices from 2.1 and would rather not have to stop at 2.3 if it's soon.

Couple weeks, at most, would be my estimate.

**Comment by datagitlies** [comment]
@dyroberts I'm happy to report that everything appears to be working in my application while using `3.2.0.BUILD-SNAPSHOT`. However, my application may not be the best test candidate as I ended up using `spring-config-use-legacy-processing=true` and adding the below dependency to our `pom.xml` file due to some other (unrelated to `spring-cloud-services-starters`) issues I was having.

```xml
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-starter-bootstrap</artifactId>
</dependency>
```

**Comment by nniesen** [comment]
@dyroberts Thanks for the update, very much appreciated!

I just tried a service with Boot 2.4.2, Cloud 2020.0.0, and SCS 3.2.0.BUILD-SNAPSHOT and was able to successfully deploy in PCF and run acceptance tests. The only thing I noticed with that cursory test is that the actuator status for `clientConfigServer` isn't reporting properly but the config is being served up so the application works.
```
{"status":"UP","components":{"clientConfigServer":{"status":"UNKNOWN","details":{"error":"no property sources located"}}, ...
```

**Comment by dyroberts** [comment]
> @dyroberts I'm happy to report that everything appears to be working in my application while using `3.2.0.BUILD-SNAPSHOT`. However, my application may not be the best test candidate as I ended up using spring-config-use-legacy-processing=true and adding the below dependency to our `pom.xml` file due to some other (unrelated to `spring-cloud-services-starters`) issues I was having.
> 
> ```
> <dependency>
> 	<groupId>org.springframework.cloud</groupId>
> 	<artifactId>spring-cloud-starter-bootstrap</artifactId>
> </dependency>
> ```
> 
> EDIT: It turns out that I'm able to use spring boot `2.4.0`, spring cloud `2020.0.0` , and `spring-cloud-services-dependencies` version `3.1.6.RELEASE` as long as I include the above dependency. So I'm good for now. I'd like to not be dependent on `spring-cloud-starter-bootstrap` but that's a totally separate issue with a different (internal to my company) dependency.

I guess I've got bad news for you then. v3.2.0 of spring-cloud-services-starters will include spring-cloud-starter-bootstrap dependency. That's for config-client only, not service-registry.

**Comment by dyroberts** [comment]
@datagitlies ^^

**Comment by datagitlies** [comment]
Ahh... I see that now in [`build.gradle`](https://github.com/pivotal-cf/spring-cloud-services-starters/blob/master/spring-cloud-services-starter-config-client/build.gradle#L27) - interesting.  I am just trying to "go with the flow" in terms of how [spring-boot prefers to import configuration](https://spring.io/blog/2020/12/22/spring-cloud-2020-0-0-aka-ilford-is-available) in v2.4.X

> **Spring Cloud Commons**
>NOTE: Bootstrap has been disabled by default. The new way of importing configuration is via the new `spring.config.import` functionality provided by Spring Boot 2.4. Please see the appropriate documentation for [Config Client](https://docs.spring.io/spring-cloud-config/docs/3.0.0/reference/html/#config-data-import), [Consul](https://docs.spring.io/spring-cloud-consul/docs/3.0.0/reference/html/#config-data-import), [Vault](https://docs.spring.io/spring-cloud-vault/docs/3.0.0/reference/html/#client-side-usage), and [Zookeeper](https://docs.spring.io/spring-cloud-zookeeper/docs/3.0.0/reference/html/#config-data-import) for details on how to use them with the new config import.
>
>If you require the legacy bootstrap functionality add the `org.springframework.cloud:spring-cloud-starter-bootstrap dependency` to your project.

Will this project be updated to _NOT_ rely on the legacy bootstrap functionality at some point @dyroberts?

**Comment by dyroberts** [comment]
> @dyroberts Thanks for the update, very much appreciated!
> 
> I just tried a service with Boot 2.4.2, Cloud 2020.0.0, and SCS 3.2.0.BUILD-SNAPSHOT and was able to successfully deploy in PCF and run acceptance tests. The only thing I noticed with that cursory test is that the actuator status for `clientConfigServer` isn't reporting properly but the config is being served up so the application works.
> 
> ```
> {"status":"UP","components":{"clientConfigServer":{"status":"UNKNOWN","details":{"error":"no property sources located"}}, ...
> ```

@nniesen Is this using a spring sample app? If not, it might be useful to make a public git rep to expose the problem and log a separate issue.

**Comment by dyroberts** [comment]
@datagitlies Yes, most likely. I can't say for sure how soon that would be though.

**Comment by datagitlies** [comment]
Ok, thanks for the info @dyroberts - no rush from my perspective, I've got some issues to sort out with with a different (internal to my company) dependency that requires `spring-cloud-starter-bootstrap` anyways.  As long removing the dependency is on the radar for this project that's all I need to know.

**Comment by nniesen** [comment]
> @nniesen Is this using a spring sample app? If not, it might be useful to make a public git rep to expose the problem and log a separate issue.

@dyroberts Nope, that's from a service using a larger library stack. I'll have to see if I can put together a reproducer or maybe track it down in debug. I do have `eureka.client.enabled=false` because otherwise the DiscoveryClient throws exceptions every 5 seconds trying to connect to an unknow server. I think it was a switch from the java-cfenv libraries to the scs starters that caused the Eureka client to start being auto-configured.

**Comment by datagitlies** [comment]
@nniesen let me know if you open another issue. I figured I might as well check and sure enough my `/health` actuator was working fine before the update and now it's showing the same thing as yours:

```json
{
	"status":"UP",
	"components":{
		"clientConfigServer":{
			"status":"UNKNOWN",
			"details":{
				"error":"no property sources located"
			}
		}
	}
}
```

**Comment by dyroberts** [comment]
Continuing this conversation in #178
