### ISSUE TITLE
Spring Boot 2 Support

### ISSUE THREAD

**Issue by azizabah** [pivotal-cf/spring-cloud-services-starters#18]
I am working on upgrading one of our services that runs inside PCF to SB 2 and ran into an issue with this not having a working version for SB 2. Is there an ETA on that or a better place to track that? Thanks.

**Comment by azizabah** [comment]
Agreed. At least it's scheduled and not that far out. Thanks for the info!

**Comment by ojhughes** [comment]
Initial Boot 2.0.x support available in SCS Starters 2.0.0.M1, see 130f032 

Note this is a Milestone release and not suitable for production yet
