### ISSUE TITLE
actuator/refresh doesn't work with 3.2.1

### ISSUE THREAD

**Issue by artemy** [pivotal-cf/spring-cloud-services-starters#200]
With spring-cloud-services-starter-config-client 3.2.1 actuator/refresh doesn't detect any updated properties anymore.
Downgrading it to 3.2.0 fixes the issue.
Dependencies used:
spring-boot 2.4.5
spring-cloud-dependencies 2020.0.2
spring-cloud-services-dependencies 3.2.1.RELEASE

I saw this known issue spring-cloud/spring-cloud-commons#913 in the release notes of the 3.2.1.RELEASE, which is supposed to be solved, but that's not the case.

One particular peculiarity is that the issue doesn't seem to be reproducable locally, only in PCF.

Sample app: https://github.com/artemy/spring-cloud-config-refresh-sample
## Steps to reproduce: 
1. Create config server `artem-config` in pcf. [This](https://github.com/artemy/spring-cloud-config-refresh-sample/blob/master/dev/config-server/src/main/resources/spring-cloud-config-refresh-local.yml) file can be used as a sample config
1. deploy `app/target/app.jar` to PCF using [manifest.yml](https://github.com/artemy/spring-cloud-config-refresh-sample/blob/master/app/manifest.yml)
1. update `app.name` property in the config server and refresh the application by calling `/actuator/refresh`
1. See the following line in the application log
    ```bash
    c.g.a.s.app.MyAwesomeApplication         : Changed properties []
    ```

## Expected behavior:
- See the following line in the application log
    ```bash
    c.g.a.s.app.MyAwesomeApplication         : Changed properties [app.name]
    ```

**Comment by spikymonkey** [comment]
Thanks very much for submitting this issue and test case. I've checked it out and confirmed it'll be fixed in Starters 3.3.0, which we hope to be releasing soon once we've completed some further validation.
