### ISSUE TITLE
Incompatible Spring Boot and Spring Cloud versions in build

### ISSUE THREAD

**Issue by snicoll** [pivotal-cf/spring-cloud-services-starters#24]
The build seems to be using [Spring Boot 1.x together with Spring Cloud Finchley](https://github.com/pivotal-cf/spring-cloud-services-starters/blob/aa4cc312d146ef2535cdab6d230e2cb36d3c5021/spring-cloud-services-dependencies-parent/pom.xml#L39) which is incompatible.

Once you properly switch to 2.0, you'll probably notice that [this dependency is no longer managed](https://github.com/pivotal-cf/spring-cloud-services-starters/blob/master/spring-cloud-services-starter-service-registry/pom.xml#L41).

**Comment by ojhughes** [comment]
Thanks, the explicit Boot dependencies will be removed in #22 as part of `M2` release

**Comment by snicoll** [comment]
> Add dependency management for Spring Security OAuth because it is no
longer managed by Spring Boot

That is  inaccurate. The dependency I was referring to is `org.springframework.security.oauth:pring-security-oauth2-client` which never was part of Spring Security (that's the former [Spring Security OAuth](https://github.com/spring-projects/spring-security-oauth) project). We've removed dependency management for that project in Spring Boot 2 as those features are being migrated to Spring Security `5.x` (not complete, that's why [this project exists](https://github.com/spring-projects/spring-security-oauth2-boot)).

In 454d082 you have switched to a standard Spring Security 5 artifact (good!) for which [we provide dependency management](https://github.com/spring-projects/spring-boot/blob/982a110fc1ee3843da3daa6bde5bfe71b69aa610/spring-boot-project/spring-boot-dependencies/pom.xml#L2701).

Can someone please reopen and remove the spring security override there?
