### ISSUE TITLE
Unable to use spring-cloud-services-dependencies v3.5.1

### ISSUE THREAD

**Issue by abraham-macias** [pivotal-cf/spring-cloud-services-starters#307]
Hi, I'm unable to use spring-cloud-services-dependencies v3.5.1 (any other version works fine).

After taking a look into the POM file in https://search.maven.org/artifact/io.pivotal.spring.cloud/spring-cloud-services-dependencies/3.5.1/pom I saw that there are no dependencies (any other version has dependencies).

Can you please take a look into this?

Thanks

**Comment by kvmw** [comment]
Fixed in v3.5.2
