### ISSUE TITLE
Maven POM for spring-cloud-services-starter-config-client version 3.5.1 is invalid

### ISSUE THREAD

**Issue by aduursma** [pivotal-cf/spring-cloud-services-starters#309]
Good afternoon,

I just upgraded to version 3.5.1 of the spring-cloud-services-starter-config-client and and my Maven build displays the following:

[WARNING] The POM for io.pivotal.spring.cloud:spring-cloud-services-starter-config-client:jar:3.5.1 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details

The transitive dependencies are indeed not available at runtime resulting in my Spring Boot app not being able to load it;s properties from the Config Server.

Is this issue reported already? Maybe it's a known issue?

Best regards,

André Duursma

**Comment by kvmw** [comment]
#307 307

**Comment by kvmw** [comment]
Fixed in v3.5.2
