### ISSUE TITLE
Pivotal Spring Cloud Services Dependencies v3.5.0 - 401 - Unauthorized Error - when communicating with Config Server 

### ISSUE THREAD

**Issue by chayaputhran** [pivotal-cf/spring-cloud-services-starters#319]
We recently migrated our application to Spring Boot 2.7.6 as part of this migration we also upgraded Spring Cloud Service Dependencies version to 3.5.0 (BOM)

```implementation platform('io.pivotal.spring.cloud:spring-cloud-services-dependencies:3.5.0')```

After this upgrade, we are seeing the below error when trying to communicate with the Config Server,

```c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: 401 Unauthorized: [no body]```

When analyzing the code of ```io.pivotal.spring.cloud.config.client.ConfigClientOAuth2BootstrapRegistryInitializer``` the ```initialize(BootstrapRegistry registry)``` method below is constructing the ```RestTemplate``` with the ```OAuth2AuthorizedClientHttpRequestInterceptor``` but the RestTemplate is not assigned to the   ```org.springframework.cloud.config.client.ConfigServicePropertySourceLocator``` instance. 
```
       @Override
	public void initialize(BootstrapRegistry registry) {
		if (!CONFIG_CLIENT_IS_PRESENT || !OAUTH2_CLIENT_IS_PRESENT || !JAVA_CFENV_IS_PRESENT)
			return;

		CfEnv cfEnv = new CfEnv();
		List<CfService> configServices = cfEnv.findServicesByTag("configuration");
		if (configServices.size() != 1)
			return;
		CfCredentials credentials = configServices.stream().findFirst().get().getCredentials();

		registry.register(RestTemplate.class, context -> {
			String clientId = credentials.getString("client_id");
			String clientSecret = credentials.getString("client_secret");
			String accessTokenUri = credentials.getString("access_token_uri");
			RestTemplate restTemplate = new RestTemplate();
			ClientRegistration clientRegistration = ClientRegistration.withRegistrationId("config-client")
					.clientId(clientId).clientSecret(clientSecret).tokenUri(accessTokenUri)
					.authorizationGrantType(AuthorizationGrantType.CLIENT_CREDENTIALS).build();
			restTemplate.getInterceptors().add(new OAuth2AuthorizedClientHttpRequestInterceptor(clientRegistration));
			return restTemplate;
		});
	}
```
We feel this missing interceptor is causing the above mentioned ```401 Unauthorized error```.

However, If we downgrade the Spring Cloud Service Dependencies version to 3.2.0.RELEASE (BOM)

```implementation platform('io.pivotal.spring.cloud:spring-cloud-services-dependencies:3.2.0.RELEASE')```

The communication to the config server happens without any issues.

Here, when analyzing the code of ```io.pivotal.spring.cloud.config.client.ConfigClientOAuth2BootstrapConfiguration``` we see the below code in the ```init()``` method.
```
       @PostConstruct
	public void init() {
		RestTemplate restTemplate = new RestTemplate();
		ClientRegistration clientRegistration = ClientRegistration.withRegistrationId("config-client")
				.clientId(configClientOAuth2Properties.getClientId())
				.clientSecret(configClientOAuth2Properties.getClientSecret())
				.tokenUri(configClientOAuth2Properties.getAccessTokenUri())
				.authorizationGrantType(AuthorizationGrantType.CLIENT_CREDENTIALS).build();
		restTemplate.getInterceptors().add(new OAuth2AuthorizedClientHttpRequestInterceptor(clientRegistration));
		locator.setRestTemplate(restTemplate);
	}
```

The locator instance ```private final ConfigServicePropertySourceLocator locator;``` is assigned with the ```RestTemplate``` that includes the ```OAuth2AuthorizedClientHttpRequestInterceptor```.

We are not sure, how to go about using the Spring Cloud Service Dependencies version 3.5.0 and communicate with the Config Server without facing the 401 - Unauthorized Error, please clarify.

**Comment by kvmw** [comment]
@chayaputhran  

By default you should not need `ConfigServicePropertySourceLocator`.  Do you have any specific configuration to enable and instantiate this bean?  
The `RestTemplate` object which is configured in `ConfigClientOAuth2BootstrapRegistryInitializer`  is used during the bootstrap phase to load the remote property sources. Here is the **[cook sample app](https://github.com/spring-cloud-services-samples/cook)** using latest version of scs-starters. It might help to compare your configuration against this sample and find the differences. 

Do you by any chance need `ConfigResourceClient` (text or binary) in your application? There is known issue related to this resource which we are fixing currently.

**Comment by chayaputhran** [comment]
@kvmw Thank you for checking this, you are right we should not be needing the ```ConfigServicePropertySourceLocator``` However, the ```ConfigServerConfigDataLoader``` class is always loading the data from my local application.properties with this new upgrade, it is not able to read the data from my config server, not sure why. We compared the dependencies and matched almost everything as per your example, the only difference is that we are using JDK 11, in your case it is JDK 8 which sould not be a problem, I guess. Things just start to work automatically without any issues if we start using the ```implementation platform('io.pivotal.spring.cloud:spring-cloud-services-dependencies:3.2.0.RELEASE')``` instead of ```implementation platform('io.pivotal.spring.cloud:spring-cloud-services-dependencies:3.5.0')``` 

Anyways, thank you so much for taking time to look into this and responding back, we are trying other options like re-creating the config server etc., in the mean time if you happen to find anything that we might be missing please let us know.

**Comment by kvmw** [comment]
@chayaputhran  just few followup questions:
- Have you enabled the `bootstrap` by any chance?  It can be enabled by adding dependency to`spring-cloud-starter-bootstrap` or  setting `spring.cloud.bootstrap.enabled=true` . If the answer is yes, then we know why `ConfigServicePropertySourceLocator` is there.  

- What is the current version of spring-boot (before above change) in your project?  Are you upgrading from 2.3.x or earlier version?

**Comment by chayaputhran** [comment]
@kvmw 

- You are right, we have the dependency spring-cloud-starter-bootstrap
- We are trying to Upgrade our Spring Boot from 2.6.8 to 2.7.6

**Comment by chayaputhran** [comment]
@kvmw 

After removing the dependency spring-cloud-starter-bootstrap, the ```ConfigServicePropertySourceLocator``` is not being used and we do not see the 401 Un-authorized errors, however, the ```ConfigServerConfigDataLoader``` is only loading the ConfigData from the local ```application.properties``` file but not from the Config Server.

**Comment by chayaputhran** [comment]
@kvmw 

Yes, we are using the below dependencies like you mentioned above

```
implementation platform('io.pivotal.spring.cloud:spring-cloud-services-dependencies:3.5.0')
implementation platform('org.springframework.cloud:spring-cloud-dependencies:2021.0.5')

implementation 'io.pivotal.spring.cloud:spring-cloud-services-starter-config-client'
	
```

And we also see the log that you mentioned above which looks something like this,

```
o.s.c.c.c.ConfigServerConfigDataLoader : Fetching config from server at : https://config-server-<encoded string>.<our domain>
```

**Comment by chayaputhran** [comment]
@kvmw 

When I debug the ```ConfigServerConfigDataLoader``` I see the below output,

```
o.s.c.c.c.ConfigServerConfigDataLoader : Located environment: name=application, profiles=[dev], label=null, version=null, state=null
o.s.c.c.c.ConfigServerConfigDataLoader : Environment application has 2 property sources with 55 properties.
```
In my understanding, one of the Property Source is having all the values from Config Server, which is exactly 55 properties, I think there is another Property Source that is getting added which has no properties, In my understanding this could be causing the problem for us here. How do we ignore the empty Property Source and use the other one with all the properties.

**Comment by kvmw** [comment]
@chayaputhran above log shows that you are loading the properties successfully from them server. empty property source should not cause any issue. If you don't see the expected properties in your app, the issue must be somewhere else. check your application name, profile and label.

**Comment by chayaputhran** [comment]
@kvmw 

Yeah!, that's what we were also thinking and looking into the things that we might be missing. But, the same application name, profile and label settings start working when we change the dependency to 

```
implementation platform('io.pivotal.spring.cloud:spring-cloud-services-dependencies:3.2.0.RELEASE')
```
Just FYI, the GitHub repo does not have any folders, the branch name is 'main', in the root of the branch itself and we have the application-dev.properties file. We have configured our Config Server to point to this correct repo and the label property is set to branch - 'main'

**Comment by kvmw** [comment]
@chayaputhran do you have `bootstrap.yaml` or `bootstrap.properties` in your app? I am asking because you had dependency to `spring-cloud-starter-bootstrap` and is likely that those files still exist in your app. If the answer is yes, they need to be removed. the content can be moved to application.properties/yaml. 

You may also enable `actuator/env` endpoint and check the loaded properties and compare them with `application-dev.properties` in your repo. 

Finally, please provide a minimal app which can reproduce above issue for further debugging.

**Comment by chayaputhran** [comment]
@kvmw 

There is no ```bootstrap.yaml``` or ```bootstrap.properties``` in our app. I just checked that. When I check the ```actuator/env```

It is not showing up the Config Server properties (```application-dev.properties```), it is just showing the ```classpath:application.properties``` file

Please find attached minimal version of our app for your reference, the app just reads one property and displays in console the value of the property in the main application itself in the ```@PostConstruct``` method, the property always is being from the local property file instead of reading it from the Config Server, in our PCF we have bound the Config Server to this app still the property value is not read from the Config Server, however, is we change the dependency to

```implementation platform('io.pivotal.spring.cloud:spring-cloud-services-dependencies:3.2.0.RELEASE')```

Please see if this is the same behavior at your end as well.
[sb276conftest.zip](https://github.com/pivotal-cf/spring-cloud-services-starters/files/10350755/sb276conftest.zip)

**Comment by kvmw** [comment]
@chayaputhran 
The problem was `spring.config.use-legacy-processing=true` in the `application.properties`.  This flag changes your application config processing to legacy mode (spring boot 2.3.x). spring boot 2.4.0+ config processing has changed a lot.  Checking the release notes i see [3.2.1.RELEASE](https://github.com/pivotal-cf/spring-cloud-services-starters/releases/tag/v3.2.1.RELEASE) is the first release that has switched to new config processing approach. that's way your code has been working with 3.2.0-RELEASE without any issue. 

I was able to run the sample app successfully after removing the above flag.

**Comment by chayaputhran** [comment]
@kvmw 

We tried removing the flag as well, but still the same issue. We tried to ```Autowire``` the environment variable in our application and print all the variables from all the available ```PropertySources```, the Config Server data is not at all available in any of the ```PropertySources```. Attached is the Java file in which we made this change to view the variables. Please suggest if you can think of anything that we could be missing at our end.

[Sb276conftestApplication.txt](https://github.com/pivotal-cf/spring-cloud-services-starters/files/10360736/Sb276conftestApplication.txt)

**Comment by chayaputhran** [comment]
@kvmw 

My bad, even though the property ```spring.config.use-legacy-processing=true``` was removed in the ```application.properties```. It was not removed from our config server, hence the issue, after removing it from config server properties file as well, things started to work with the dependency 
```
implementation platform('io.pivotal.spring.cloud:spring-cloud-services-dependencies:3.5.0')
```

But, still curious, we followed the instructions in https://spring.io/blog/2020/08/14/config-file-processing-in-spring-boot-2-4

before using the ```spring.config.use-legacy-processing=true``` property in our property files but was not sure that it will cause this sort of problems when we upgrade our  ```spring-cloud-services-dependencies```, may be we missed something during our changes. 

Thank you so much for the help!!
