### ISSUE TITLE
Cloud Foundry Certificate Truster

### ISSUE THREAD

**Issue by azizabah** [pivotal-cf/spring-cloud-services-starters#50]
Is it really necessary for this package:
```
<dependency>
	<groupId>io.pivotal.spring.cloud</groupId>
	<artifactId>cloudfoundry-certificate-truster</artifactId>
</dependency>
```
to be a part of the starters such as the service registry starter?

My concern is taken from the library's GitHub repo:
"Use of this library is strongly discouraged. Providing a library that essentially disables or bypasses a major facet of inter-application communication security, while convenient for development, also makes it easy for developers to deploy insecure applications to production. Platforms like Cloud Foundry have made it easier to centralize SSL certificate management at an operations level, eliminating any need for a library like this. As such, this library is not being actively maintained and there are no plans to publish further releases of the library"

By including it with the service registry starter, you are unintentionally exposing anyone that uses it to a massive security risk if they accidentally leak out a TRUST_CERTS environment variable or a machine becomes compromised and that variable is set.

**Comment by azizabah** [comment]
@royclarkson - any thoughts?

**Comment by scottfrederick** [comment]
@azizabah We recognize the need to remove `cloudfoundry-certificate-truster` from the `spring-cloud-services-starters`. Removal of the library will require additional documentation and support articles to instruct users how to configure Cloud Foundry and how to troubleshoot problems when self-signed certificates or internal CA certificates are being used in the platform. This will be scheduled for a future release. 

cc @csterwa

**Comment by ojhughes** [comment]
Hey @azizabah Just to clarify, the `TRUST_CERTS` variable contains the domain that should be trusted, not the actual certificate data. Either way we should look to remove the dependency as it is deprecated

**Comment by azizabah** [comment]
@scottfrederick - Sounds good. I understand the desire to make sure folks are not blind-sided by by this kind of a change. 
@ojhughes  - Yup I'm aware. It's easily the most useful / terrifying library all in one. :)

**Comment by dyroberts** [comment]
This library is removed in the 3.0.0.RELEASE
