### ISSUE TITLE
Upgrade to latest Spring Boot 2.1.x version

### ISSUE THREAD

**Issue by tzolov** [pivotal-cf/spring-cloud-services-starters#57]
Wille `Spring Boot` is already at version `2.1.2.RELEASE`, the `spring-cloud-services` is still at boot `2.0.3`:
 https://github.com/pivotal-cf/spring-cloud-services-starters/blob/master/spring-cloud-services-dependencies-parent/pom.xml#L39

Projects that depends on and use `spring-cloud-services` (such as Spring Cloud Skipper) may not be able to upgrade to latest boot 2.1.x 

Related to https://github.com/spring-cloud/spring-cloud-skipper/issues/750

**Comment by csterwa** [comment]
@tzolov with the upcoming milestone releases of Spring Cloud Greenwich, we will be working on getting a Spring Boot `2.1.x.RELEASE` compatible version of the SCS dependencies soon. We'll keep this updated as we make progress. Thank you.

**Comment by csterwa** [comment]
@sabbyanandan here is the SCS Connectors issue to track: https://github.com/pivotal-cf/spring-cloud-services-connector/issues/88

**Comment by csterwa** [comment]
@sabbyanandan @tzolov SCS Connectors/Starters version 2.1.0.M1 has been released and includes upgrade to Spring Cloud Greenwich and Spring Boot 2.1.
