### ISSUE TITLE
Spring Cloud Services incorrectly handles Environment

### ISSUE THREAD

**Issue by jxblum** [pivotal-cf/spring-cloud-services-starters#59]
In a nutshell, when the `org.springframework.cloud:spring-cloud-services-starter-service-registry` dependency is added to the CLASSPATH of a _Spring Boot_, Pivotal GemFire `ClientCache` application deployed to PCF, connected to PCC, the dependency loses critical, contextual information stored in the `Environment` by _Spring Boot for Pivotal GemFire_ ([SBDG](https://github.com/spring-projects/spring-boot-data-geode)) using a custom `PropertySource`.

As a result, the _Spring Boot_, Pivotal GemFire `ClientCache` application (based on SBDG) is unable to authenticate and connect to the PCC instance deployed in PCF.

You can successfully reproduce this issue by doing the following:

1. Clone the [SBDG](https://github.com/spring-projects/spring-boot-data-geode) project.

2. Create a _topic branch_ from `1.0.0.M3` ([here](https://github.com/spring-projects/spring-boot-data-geode/tree/1.0.0.M3)).

> NOTE: You cannot simply branch from the HEAD of `master` since I have already checked in a "workaround" to this issue in [commit 2e26325](https://github.com/spring-projects/spring-boot-data-geode/commit/2e263257f2500adb204cd07ce24927d9a8eb4810).

3. Add the `org.springframework.cloud:spring-cloud-services-starter-service-registry` to the CLASSPATH of the SBDG `spring-geode-autoconfigure` module (for [example](https://github.com/spring-projects/spring-boot-data-geode/blob/master/spring-geode-autoconfigure/spring-geode-autoconfigure.gradle#L32-L34)).

4.  Then, run the [`AutoConfiguredCloudSecurityContextIntegrationTest`](https://github.com/spring-projects/spring-boot-data-geode/blob/master/spring-geode-autoconfigure/src/test/java/org/springframework/geode/boot/autoconfigure/security/auth/cloud/AutoConfiguredCloudSecurityContextIntegrationTests.java) class and see the test fail!

Without the `org.springframework.cloud:spring-cloud-services-starter-service-registry` dependency on the CLASSPATH, the `AutoConfiguredCloudSecurityContextIntegrationTest` passes as expected.

After in-depth analysis, my debugging revealed the main culprit in this issue involves the [`BootstrapApplicationListener`](https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/BootstrapApplicationListener.java) class.

In summary...

The `BootstrapApplicationListener`, as its name implies, creates a new (temporary) "bootstrap" `ApplicationContext` along with a new (also, temporary) `Environment` object.  This "bootstrap" context becomes the "parent" of the main `ApplicationContext` started/initialized by the _Spring Boot_ application on startup.  The `BootstrapApplicationListener` additionally copies/removes critical information (e.g. a SBDG custom `PropertySource`) from the main `Environment` to the "bootstrap" `Environment` object, which is later discarded from the "bootstrap" `Environment`.  This "bootstrap" `Environment` is somehow passed to the SDG Security configuration handling classes, thus causing the underlying SDG `@Configuration` class used to authenticate the GemFire `ClientCache` app instance with PCC in PCF to not have the necessary Security (auth) credentials available to it upon inspecting the `Environment`, leading to an eventual authentication error.

Anyway, I tracked the beginning of this issue down to this [snippet of code](https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/BootstrapApplicationListener.java#L253).  
Because SBDG used a `PropertiesPropertySource` to capture the Security (auth) credentials from the VCAP environment into a custom named `PropertySource`, and the _Spring_ `PropertiesPropertySource` is an `EnumerablePropertySource`, this is how the SBDG custom name `PropertySource` gets copied and lost, unlike other `PropertySources`, which _Spring Boot_ adds, that won't get lost because they are not `EnumerablePropertySources`. :(

Additional details for this problem will be provided below, in follow up comments.

**Comment by habuma** [comment]
To be clear: `BootstrapApplicationListener` is in Spring Cloud Commons, part of OSS Spring Cloud and not Spring Cloud Services. Spring Cloud Services Starters has Spring Cloud Commons as a dependency in its build, but if the core of the problem is in `BootstrapApplicationListener`, then the bug should be filed with that project, not with Spring Cloud Services Starters.

**Comment by jxblum** [comment]
Closing issue!  Please see https://github.com/spring-cloud/spring-cloud-commons/issues/476, instead.

However, you should be aware that this problem was an issue that first came up in the context of Spring Cloud Services (specifically, with the Service Registry; see [here](https://pivotal.slack.com/archives/CEKHXHCJU/p1545836217002000)) since the users were using the Service Registry to register and coordinate/orchestrate several of their microservice based _Spring Boot_ apps in PCF.
