### ISSUE TITLE
Update reference of Spring Cloud Greenwich.RC2 version

### ISSUE THREAD

**Issue by fduser1** [pivotal-cf/spring-cloud-services-starters#60]
Greenwich.RELEASE is available now. `spring-cloud.version` should be updated:

https://github.com/pivotal-cf/spring-cloud-services-starters/blob/master/spring-cloud-services-dependencies-parent/pom.xml#L40

Currently I am facing a missing dependency error since I do not have the spring milestone repo added to my project.

**Comment by royclarkson** [comment]
Closed in #61
