### ISSUE TITLE
Error with dependencies in version 2.1.1.RELEASE of spring-cloud-services-starter-service-registry

### ISSUE THREAD

**Issue by ecristobal** [pivotal-cf/spring-cloud-services-starters#85]
Hi everyone!

I'm trying to use in my project the following BOM for Pivotal Spring Cloud:
```xml
<dependency>
    <groupId>io.pivotal.spring.cloud</groupId>
    <artifactId>spring-cloud-services-dependencies</artifactId>
    <version>2.1.2.RELEASE</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
```

But, when I import the starter for the Service Registry:
```xml
<dependency>
    <groupId>io.pivotal.spring.cloud</groupId>
    <artifactId>spring-cloud-services-starter-service-registry</artifactId>
</dependency>
```
I'm getting an error because Maven can't download the following transitive artifact, as it's not available on Maven Central:
io.pivotal.spring.cloud:spring-cloud-services-cloudfoundry-connector:jar:**2.1.1.RELEASE**.

This error happens because the only available versions are 2.1.2.RELEASE and 2.1.0.RELEASE. Shouldn't it be pointing to the first one instead of the 2.1.1.RELEASE?

Thanks and regards,

Esteban

**Comment by habuma** [comment]
This should be fixed now, although Initializr has been rolled back to serving up pom.xml files with 2.1.0.RELEASE dependencies. So if you start a new project, you'll need to manually set `spring-cloud-services.version` to `2.1.2.RELEASE` until we can get that version reinstated in Initializr.

**Comment by habuma** [comment]
Oh...and although it's confusing, 2.1.2.RELEASE starters is supposed to point to 2.1.1.RELEASE of connectors. That's because there was a starters update that didn't require a connectors update. (Yes, I know that there's a 2.1.2.RELEASE of connectors, but that's a different story.)
