### ISSUE TITLE
Remove 3rd party dependency from BOM

### ISSUE THREAD

**Issue by snicoll** [pivotal-cf/spring-cloud-services-starters#86]
A BOM should not define dependency management for artifacts that it does not manage directly. The current BOM has dependency management for [spring security](https://github.com/pivotal-cf/spring-cloud-services-starters/blob/643fbf20a1cdbd670b8decb762d203a7bb32c26e/spring-cloud-services-dependencies/pom.xml#L77-L82) that should be removed.

**Comment by habuma** [comment]
@snicoll Just for clarity's sake, are you suggesting that the `spring-security-oauth2` dependency be removed from `spring-cloud-services-dependencies/pom.xml`? (And, of course, adjusting the references in our starters to explicitly declare the version if necessary.)

**Comment by snicoll** [comment]
Yes. You can’t force a version of an artifact you’re not managing directly

**Comment by habuma** [comment]
@snicoll Can you take a look at the changes in https://github.com/pivotal-cf/spring-cloud-services-starters/pull/89 and let me know if you think they're acceptable? Thanks

**Comment by snicoll** [comment]
@habuma didn't get a chance to review before it got merged but LGTM. Thanks for asking
